## Importing Libraries

In [549]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib as plt
from sklearn import linear_model

## Importing the Train Data

In [550]:
trdata=pd.read_csv('train.csv')
trdata=pd.DataFrame(trdata)

In [703]:
trdata.head()

checkout_price  base_price  num_orders  op_area
0          136.83      152.29         177      2.0
1          136.83      135.83         270      2.0
2          134.86      135.86         189      2.0
3          339.50      437.53          54      2.0
4          243.50      242.50          40      2.0

In [708]:
np.mean(trdata['num_orders'])

261.8727603669275

## Importing the Meal Info Table

In [552]:
meal_info=pd.read_csv('meal_info.csv')
meal_info=pd.DataFrame(meal_info)

In [553]:
meal_info.head()

meal_id   category cuisine
0     1885  Beverages    Thai
1     1993  Beverages    Thai
2     2539  Beverages    Thai
3     1248  Beverages  Indian
4     2631  Beverages  Indian

## Importing the Fulfilment Center Table

In [554]:
fcenter_info=pd.read_csv('fulfilment_center_info.csv')
fcenter_info=pd.DataFrame(fcenter_info)

In [555]:
fcenter_info.head()

center_id  city_code  region_code center_type  op_area
0         11        679           56      TYPE_A      3.7
1         13        590           56      TYPE_B      6.7
2        124        590           56      TYPE_C      4.0
3         66        648           34      TYPE_A      4.1
4         94        632           34      TYPE_C      3.6

In [556]:
fcenter_info.count()

center_id      77
city_code      77
region_code    77
center_type    77
op_area        77
dtype: int64

In [557]:
trdata.count()

id                       456548
week                     456548
center_id                456548
meal_id                  456548
checkout_price           456548
base_price               456548
emailer_for_promotion    456548
homepage_featured        456548
num_orders               456548
dtype: int64

In [558]:
meal_info.count()

meal_id     51
category    51
cuisine     51
dtype: int64

In [560]:
#centv=trdata['center_id'].values
print (centv)

[55 55 55 ... 61 61 61]


In [561]:
centype=[]
op_area=[]
c=fcenter_info['center_id'].values

In [562]:
print (c)

[ 11  13 124  66  94  64 129 139  88 143 101  86  32 149 152  92  27  14
  26 104  77  23  97 146 113 145  80  55 186  99  91  20 106  81  73  29
  43 102  61  50  83  57 126 177  67 174  59  58  65  39 132  89 162  75
  72  41  10 110  52  93  74  34 137 153  24 109 108  36 157  17 161  42
  53  30  76  68  51]


## Extracting center_type & op_area from Fulfilment Center Table

In [563]:
i=-1
for a in centv:
    for b in c:
        i=i+1
        if a==b:
            centype.append(fcenter_info.center_type[i])
            op_area.append(fcenter_info.op_area[i])
            i=-1
            break         
           

In [564]:
center_type=pd.DataFrame(centype,columns=['center_type'])
center_type.count()

center_type    456548
dtype: int64

In [565]:
op_area=pd.DataFrame(op_area,columns=['op_area'])
op_area.count()

op_area    456548
dtype: int64

## Combining centype and op_area columns to Train Data Table

In [566]:
trdata=pd.concat([trdata,center_type,op_area],axis=1)

In [567]:
trdata.isnull().sum()

id                       0
week                     0
center_id                0
meal_id                  0
checkout_price           0
base_price               0
emailer_for_promotion    0
homepage_featured        0
num_orders               0
center_type              0
op_area                  0
dtype: int64

## Repeating the process for Meal Info Table

In [568]:
mealv=trdata['meal_id'].values
print (mealv)

[1885 1993 2539 ... 2664 2569 2490]


In [569]:
categ=[]
cuis=[]
d=meal_info['meal_id'].values

In [493]:
print (d)

[1885 1993 2539 1248 2631 1311 1062 1778 1803 1198 2707 1847 1438 2494
 2760 2490 1109 2290 1525 2704 1878 2640 2577 1754 1971 2306 2139 2826
 2664 2569 1230 1207 2322 2492 1216 1727 1902 1247 2304 1543 1770 2126
 1558 2581 1962 1571 2956 2104 2444 2867 1445]


## Extracting Category and Cuisine Information from Meal_Info Table

In [570]:
i=-1
for a in mealv:
    for b in d:
        i=i+1
        if a==b:
            categ.append(meal_info.category[i])
            cuis.append(meal_info.cuisine[i])
            i=-1
            break

In [571]:
category=pd.DataFrame(categ,columns=['category'])
category.count()

category    456548
dtype: int64

In [572]:
cuisine=pd.DataFrame(cuis,columns=['cuisine'])
cuisine.count()

cuisine    456548
dtype: int64

## Combining Category and Cuisine data with Train Data

In [573]:
trdata=pd.concat([trdata,category,cuisine],axis=1)

In [574]:
trdata.isnull().sum()

id                       0
week                     0
center_id                0
meal_id                  0
checkout_price           0
base_price               0
emailer_for_promotion    0
homepage_featured        0
num_orders               0
center_type              0
op_area                  0
category                 0
cuisine                  0
dtype: int64

## Dropping Center_id and Meal_id from Train Data 

In [575]:
trdata.drop(['center_id','meal_id'],axis=1,inplace=True)

In [576]:
trdata.isnull().sum()

id                       0
week                     0
checkout_price           0
base_price               0
emailer_for_promotion    0
homepage_featured        0
num_orders               0
center_type              0
op_area                  0
category                 0
cuisine                  0
dtype: int64

In [577]:
traindata=trdata

In [578]:
traindata.head()

id  week  checkout_price  base_price  emailer_for_promotion  \
0  1379560     1          136.83      152.29                      0   
1  1466964     1          136.83      135.83                      0   
2  1346989     1          134.86      135.86                      0   
3  1338232     1          339.50      437.53                      0   
4  1448490     1          243.50      242.50                      0   

   homepage_featured  num_orders center_type  op_area   category cuisine  
0                  0         177      TYPE_C      2.0  Beverages    Thai  
1                  0         270      TYPE_C      2.0  Beverages    Thai  
2                  0         189      TYPE_C      2.0  Beverages    Thai  
3                  0          54      TYPE_C      2.0  Beverages  Indian  
4                  0          40      TYPE_C      2.0  Beverages  Indian

## Creating Dummy Variables for Categorical Variables 

In [579]:
hpf=pd.get_dummies(traindata["homepage_featured"],drop_first=True)
hpf.head()
efp=pd.get_dummies(traindata["emailer_for_promotion"],drop_first=True)
efp.head()
centtype=pd.get_dummies(traindata["center_type"],drop_first=True)
centtype.head()
cat=pd.get_dummies(traindata["category"],drop_first=True)
cat.head()
cuis=pd.get_dummies(traindata["cuisine"],drop_first=True)
cuis.head()

Indian  Italian  Thai
0       0        0     1
1       0        0     1
2       0        0     1
3       1        0     0
4       1        0     0

## Dropping Categorical Variables 

In [581]:
#traindata.drop(['id','week','homepage_featured','emailer_for_promotion','center_type','category','cuisine'],axis=1,inplace=True)
traindata.head()

checkout_price  base_price  num_orders  op_area
0          136.83      152.29         177      2.0
1          136.83      135.83         270      2.0
2          134.86      135.86         189      2.0
3          339.50      437.53          54      2.0
4          243.50      242.50          40      2.0

## Adding the Dummy Variables instead of the categorical variables

In [582]:
traindata=pd.concat([traindata,hpf,efp,centtype,cat,cuis],axis=1)

In [583]:
traindata.head()

checkout_price  base_price  num_orders  op_area  1  1  TYPE_B  TYPE_C  \
0          136.83      152.29         177      2.0  0  0       0       1   
1          136.83      135.83         270      2.0  0  0       0       1   
2          134.86      135.86         189      2.0  0  0       0       1   
3          339.50      437.53          54      2.0  0  0       0       1   
4          243.50      242.50          40      2.0  0  0       0       1   

   Biryani  Desert  ...  Pizza  Rice Bowl  Salad  Sandwich  Seafood  Soup  \
0        0       0  ...      0          0      0         0        0     0   
1        0       0  ...      0          0      0         0        0     0   
2        0       0  ...      0          0      0         0        0     0   
3        0       0  ...      0          0      0         0        0     0   
4        0       0  ...      0          0      0         0        0     0   

   Starters  Indian  Italian  Thai  
0         0       0        0     1  
1         0       0        0     1  
2         0       0        0     1  
3         0       1        0     0  
4         0       1        0     0  

[5 rows x 24 columns]

In [584]:
traindata2=traindata

In [585]:
traindata3=traindata

In [686]:
traindata2.head()

checkout_price  base_price  num_orders  op_area  1  1  TYPE_B  TYPE_C  \
0          136.83      152.29         177      2.0  0  0       0       1   
1          136.83      135.83         270      2.0  0  0       0       1   
2          134.86      135.86         189      2.0  0  0       0       1   
3          339.50      437.53          54      2.0  0  0       0       1   
4          243.50      242.50          40      2.0  0  0       0       1   

   Biryani  Desert  ...  Pizza  Rice Bowl  Salad  Sandwich  Seafood  Soup  \
0        0       0  ...      0          0      0         0        0     0   
1        0       0  ...      0          0      0         0        0     0   
2        0       0  ...      0          0      0         0        0     0   
3        0       0  ...      0          0      0         0        0     0   
4        0       0  ...      0          0      0         0        0     0   

   Starters  Indian  Italian  Thai  
0         0       0        0     1  
1         0       0        0     1  
2         0       0        0     1  
3         0       1        0     0  
4         0       1        0     0  

[5 rows x 24 columns]

In [687]:
dep = traindata2["num_orders"]

In [688]:
dep.count()

456548

In [691]:
#traindata3.drop(['num_orders'],axis=1,inplace=True)
traindata2.head()

checkout_price  base_price  op_area  1  1  TYPE_B  TYPE_C  Biryani  Desert  \
0          136.83      152.29      2.0  0  0       0       1        0       0   
1          136.83      135.83      2.0  0  0       0       1        0       0   
2          134.86      135.86      2.0  0  0       0       1        0       0   
3          339.50      437.53      2.0  0  0       0       1        0       0   
4          243.50      242.50      2.0  0  0       0       1        0       0   

   Extras  ...  Pizza  Rice Bowl  Salad  Sandwich  Seafood  Soup  Starters  \
0       0  ...      0          0      0         0        0     0         0   
1       0  ...      0          0      0         0        0     0         0   
2       0  ...      0          0      0         0        0     0         0   
3       0  ...      0          0      0         0        0     0         0   
4       0  ...      0          0      0         0        0     0         0   

   Indian  Italian  Thai  
0       0        0     1  
1       0        0     1  
2       0        0     1  
3       1        0     0  
4       1        0     0  

[5 rows x 23 columns]

In [445]:
#traindata3.drop(['op_area',1,'TYPE_B','TYPE_C','Extras','Pasta','Pizza','Sandwich','Seafood','Soup','Indian','Thai'],axis=1,inplace=True)

In [692]:
traindata3.head()

checkout_price  base_price  op_area  1  1  TYPE_B  TYPE_C  Biryani  Desert  \
0          136.83      152.29      2.0  0  0       0       1        0       0   
1          136.83      135.83      2.0  0  0       0       1        0       0   
2          134.86      135.86      2.0  0  0       0       1        0       0   
3          339.50      437.53      2.0  0  0       0       1        0       0   
4          243.50      242.50      2.0  0  0       0       1        0       0   

   Extras  ...  Pizza  Rice Bowl  Salad  Sandwich  Seafood  Soup  Starters  \
0       0  ...      0          0      0         0        0     0         0   
1       0  ...      0          0      0         0        0     0         0   
2       0  ...      0          0      0         0        0     0         0   
3       0  ...      0          0      0         0        0     0         0   
4       0  ...      0          0      0         0        0     0         0   

   Indian  Italian  Thai  
0       0        0     1  
1       0        0     1  
2       0        0     1  
3       1        0     0  
4       1        0     0  

[5 rows x 23 columns]

## Splitting the Train Data into Train and Test for model building/testing 

In [693]:
from sklearn.model_selection import train_test_split

In [694]:
x_train,x_test,y_train,y_test=train_test_split(traindata3,dep,test_size=0.3)

In [695]:
y_test.count()

136965

## Linear Regression Model 

In [696]:
from sklearn import linear_model
reg = linear_model.LinearRegression()

In [697]:
reg.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [698]:
reg.coef_

array([-6.72634858e-01,  2.27645296e-01,  6.98502039e+01,  2.37859581e+02,
        2.54585993e+02,  1.43804369e+01, -1.51216145e+01,  8.31377387e+01,
        8.34654574e+01, -2.09893759e+02,  9.24481059e+00, -3.25768650e+02,
       -3.19346150e+02,  5.54796620e+01,  5.94476986e+02, -5.81072628e+00,
        1.15924983e+02, -2.05249697e+01, -4.11190808e+02, -3.07469911e+02,
       -1.65332250e+02,  1.93229694e+02,  2.59181743e+02])

In [699]:
reg.intercept_

9.352744966549096

In [700]:
pred=reg.predict(x_test)
print (pred)

[   9.94772354  382.93221513 -186.10686299 ...   40.61253112  237.03986908
  121.61627168]


In [646]:
pred=pd.DataFrame(pred)

In [527]:
#y_test=pd.DataFrame(y_test)
#print(y_test) 

In [701]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

In [702]:
r2_score=reg.score(x_test,y_test)
print (r2_score)

0.4137124723061377


## lsq

In [710]:
x_train.count()

checkout_price    319583
base_price        319583
op_area           319583
1                 319583
1                 319583
TYPE_B            319583
TYPE_C            319583
Biryani           319583
Desert            319583
Extras            319583
Fish              319583
Other Snacks      319583
Pasta             319583
Pizza             319583
Rice Bowl         319583
Salad             319583
Sandwich          319583
Seafood           319583
Soup              319583
Starters          319583
Indian            319583
Italian           319583
Thai              319583
dtype: int64

## Predicted Values

In [737]:
tsdata=pd.read_csv('test_.csv')
tsdata=pd.DataFrame(tsdata)
tsdata.head()

id  week  center_id  meal_id  checkout_price  base_price  \
0  1028232   146         55     1885          158.11      159.11   
1  1127204   146         55     1993          160.11      159.11   
2  1212707   146         55     2539          157.14      159.14   
3  1082698   146         55     2631          162.02      162.02   
4  1400926   146         55     1248          163.93      163.93   

   emailer_for_promotion  homepage_featured  
0                      0                  0  
1                      0                  0  
2                      0                  0  
3                      0                  0  
4                      0                  0

In [738]:
meal_info=pd.read_csv('meal_info.csv')
meal_info=pd.DataFrame(meal_info)
meal_info.head()

meal_id   category cuisine
0     1885  Beverages    Thai
1     1993  Beverages    Thai
2     2539  Beverages    Thai
3     1248  Beverages  Indian
4     2631  Beverages  Indian

In [739]:
fcenter_info=pd.read_csv('fulfilment_center_info.csv')
fcenter_info=pd.DataFrame(fcenter_info)
fcenter_info.head()

center_id  city_code  region_code center_type  op_area
0         11        679           56      TYPE_A      3.7
1         13        590           56      TYPE_B      6.7
2        124        590           56      TYPE_C      4.0
3         66        648           34      TYPE_A      4.1
4         94        632           34      TYPE_C      3.6

In [143]:
#fcenter_info.count()
tsdata.count()
#meal_info.count()

id                       32573
week                     32573
center_id                32573
meal_id                  32573
checkout_price           32573
base_price               32573
emailer_for_promotion    32573
homepage_featured        32573
dtype: int64

In [740]:
centv=tsdata['center_id'].values
print (centv)

[55 55 55 ... 61 61 61]


In [747]:
centype=[]
op_area=[]

In [748]:
c=fcenter_info['center_id'].values
i=-1
for a in centv:
    for b in c:
        i=i+1
        if a==b:
            centype.append(fcenter_info.center_type[i])
            op_area.append(fcenter_info.op_area[i])
            i=-1
            break

In [749]:
center_type=pd.DataFrame(centype,columns=['center_type'])
center_type.count()

center_type    32573
dtype: int64

In [750]:
op_area=pd.DataFrame(op_area,columns=['op_area'])
op_area.count()

op_area    32573
dtype: int64

In [751]:
tsdata=pd.concat([tsdata,center_type,op_area],axis=1)
tsdata.isnull().sum()

id                       0
week                     0
center_id                0
meal_id                  0
checkout_price           0
base_price               0
emailer_for_promotion    0
homepage_featured        0
center_type              0
op_area                  0
dtype: int64

In [752]:
mealv=tsdata['meal_id'].values
print (mealv)

[1885 1993 2539 ... 2664 2569 2490]


In [753]:
categ=[]
cuis=[]

In [754]:
d=meal_info['meal_id'].values
i=-1
for a in mealv:
    for b in d:
        i=i+1
        if a==b:
            categ.append(meal_info.category[i])
            cuis.append(meal_info.cuisine[i])
            i=-1
            break

In [755]:
category=pd.DataFrame(categ,columns=['category'])
category.count()
cuisine=pd.DataFrame(cuis,columns=['cuisine'])
cuisine.count()

cuisine    32573
dtype: int64

In [756]:
tsdata=pd.concat([tsdata,category,cuisine],axis=1)
tsdata.isnull().sum()

id                       0
week                     0
center_id                0
meal_id                  0
checkout_price           0
base_price               0
emailer_for_promotion    0
homepage_featured        0
center_type              0
op_area                  0
category                 0
cuisine                  0
dtype: int64

In [757]:
tsdata.drop(['center_id','meal_id'],axis=1,inplace=True)
tsdata.isnull().sum()

id                       0
week                     0
checkout_price           0
base_price               0
emailer_for_promotion    0
homepage_featured        0
center_type              0
op_area                  0
category                 0
cuisine                  0
dtype: int64

In [758]:
testdata=tsdata
#testdata.isnull().sum()
testdata.head()

id  week  checkout_price  base_price  emailer_for_promotion  \
0  1028232   146          158.11      159.11                      0   
1  1127204   146          160.11      159.11                      0   
2  1212707   146          157.14      159.14                      0   
3  1082698   146          162.02      162.02                      0   
4  1400926   146          163.93      163.93                      0   

   homepage_featured center_type  op_area   category cuisine  
0                  0      TYPE_C      2.0  Beverages    Thai  
1                  0      TYPE_C      2.0  Beverages    Thai  
2                  0      TYPE_C      2.0  Beverages    Thai  
3                  0      TYPE_C      2.0  Beverages  Indian  
4                  0      TYPE_C      2.0  Beverages  Indian

In [759]:
hpf=pd.get_dummies(testdata["homepage_featured"],drop_first=True)
hpf.head()
efp=pd.get_dummies(testdata["emailer_for_promotion"],drop_first=True)
efp.head()
centtype=pd.get_dummies(testdata["center_type"],drop_first=True)
centtype.head()
cat=pd.get_dummies(testdata["category"],drop_first=True)
cat.head()
cuis=pd.get_dummies(testdata["cuisine"],drop_first=True)
cuis.head()

Indian  Italian  Thai
0       0        0     1
1       0        0     1
2       0        0     1
3       1        0     0
4       1        0     0

In [760]:
testdata.drop(['id','week','homepage_featured','emailer_for_promotion','center_type','category','cuisine'],axis=1,inplace=True)
testdata.head()

checkout_price  base_price  op_area
0          158.11      159.11      2.0
1          160.11      159.11      2.0
2          157.14      159.14      2.0
3          162.02      162.02      2.0
4          163.93      163.93      2.0

In [761]:
testdata=pd.concat([testdata,hpf,efp,centtype,cat,cuis],axis=1)

In [762]:
#testdata.head()
testdata.isnull().sum()

checkout_price    0
base_price        0
op_area           0
1                 0
1                 0
TYPE_B            0
TYPE_C            0
Biryani           0
Desert            0
Extras            0
Fish              0
Other Snacks      0
Pasta             0
Pizza             0
Rice Bowl         0
Salad             0
Sandwich          0
Seafood           0
Soup              0
Starters          0
Indian            0
Italian           0
Thai              0
dtype: int64

In [763]:
pred=reg.predict(testdata)

In [764]:
print (pred)

[322.98362709 321.63835738 323.64291227 ... 368.00748728 368.00748728
 388.08026578]


In [769]:
pred=pd.DataFrame(pred)

In [770]:
id=pd.read_csv('test_.csv')

In [771]:
id=pd.DataFrame(id)

In [772]:
id=pd.concat([id,pred],axis=1)

In [773]:
id.head()

id  week  center_id  meal_id  checkout_price  base_price  \
0  1028232   146         55     1885          158.11      159.11   
1  1127204   146         55     1993          160.11      159.11   
2  1212707   146         55     2539          157.14      159.14   
3  1082698   146         55     2631          162.02      162.02   
4  1400926   146         55     1248          163.93      163.93   

   emailer_for_promotion  homepage_featured           0  
0                      0                  0  322.983627  
1                      0                  0  321.638357  
2                      0                  0  323.642912  
3                      0                  0 -103.497921  
4                      0                  0 -104.347851

In [774]:
id.drop(['center_id','meal_id','checkout_price','base_price','emailer_for_promotion','homepage_featured'],axis=1,inplace=True)

In [775]:
id.head()

id  week           0
0  1028232   146  322.983627
1  1127204   146  321.638357
2  1212707   146  323.642912
3  1082698   146 -103.497921
4  1400926   146 -104.347851

In [776]:
id.to_csv('FinalAnswer.csv',index=True)